[package]
name = "udemy8_arrays"
version = "0.1.0"
authors = ["cmcdgit <cmcdgit@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
